"""fraud engine tables

Revision ID: d8fd88d9a9ac
Revises: e31768ee8158
Create Date: 2026-06-27 16:54:21.012657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fd88d9a9ac'
down_revision = 'e31768ee8158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
